name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Deploy only on changes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy Frontend
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "frontend"                # Folder containing the frontend files
        output_location: "dist"
        api_location: ""                        # Leave empty if backend is separate
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: "upload"
